/**
 * 站点配置表（SITE_CONFIGS）
 *
 * 按域名分组的站点提取配置。每个条目包含：
 * - contentSelectors: 正文候选容器选择器（优先级从高到低）
 * - cleanupSels: 该站点专属噪音选择器
 * - noiseClassKeywords: 用于打分的 class 噪声关键词
 * - enableDensityOptimization / blockTagThreshold: 密度优化相关
 * - titleSelectors: 标题兜底选择器
 */
import type { SiteConfig } from './index';

/**
 * 站点配置表：key 为 hostname（支持精确匹配与后缀匹配，如 cloud.tencent.com）。
 */
export const SITE_CONFIGS: Record<string, SiteConfig> = {
  // ===== 腾讯云（全配，含文档站 + 开发者社区） =====
  'cloud.tencent.com': {
    contentSelectors: [
      // 开发者社区文章页正文 Markdown 容器（最优先，精确）
      '.mod-content__markdown',
      '.rno-markdown',
      '.rno-markdown-content',
      // 腾讯云 Next.js 客户端渲染的正文容器
      '.rich-viewer',
      '.J-articleContent .markdown-body',
      'article .markdown-body',
      '.J-markdownBody', // 腾讯云文档站主容器
      '.markdown-body',
      '.doc-content',
      '.doc-detail',
      '.content-markdown',
      '#doc-content',
      '.article-detail-content',
      '#docArticleContent', // 腾讯云文档正文
      '.J-articleContent',
      '.article-content',
      '.article-body',
      '.article-detail',
      '.article-detail-bd',
      '.article-detail-main',
      '#articleContent',
      '#docContent',
      '.markdown-text',
      '.article-info-detail',
    ],
    cleanupSels: [
      // 腾讯云开发者社区文章页头部/元信息
      '.mod-header2',
      '.mod-header2__top',
      '.mod-header2__bottom',
      '.mod-header2__title',
      '.mod-header2__detail',
      '.mod-header2__infos',
      '.mod-header2__operates',
      '.mod-header2__summary',
      '.mod-article-content',
      // 腾讯云开发者社区导航
      '.cdc-header',
      '.cdc-header__inner',
      '.cdc-nav',
      '.cdc-nav__list',
      '.cdc-navbar',
      '.cdc-topbar',
      // 腾讯云开发者社区底部/页脚
      '.cdc-footer',
      '.cdc-footer__inner',
      '.mod-footer',
      '.mod-article-footer',
      '.article-footer',
      // 关键词/概述区
      '.mod-overview',
      '.mod-overview__keyword',
      // 相关推荐/更多回答
      '.mod-article-related',
      '.related-article',
      '.recommend-article',
      '.mod-recommend',
      // 评论区
      '.comment-area',
      '.comments',
      '.article-comment',
      // 侧边栏/工具栏
      '.sidebar',
      '.tool-bar',
      '.operate-area',
      // 二维码/推广/广告
      '.qr-code',
      '.qrcode',
      '.rno-qrcode',
      '.coupon-card',
      '.doc-coupon',
      '.promotion',
      '.banner',
      '.ad',
      // 通用噪音
      '.article-info',
      '.column-info',
      '.article-category',
      '.article-author',
      '.article-meta',
      '.article-tag',
      '.doc-info',
      '.doc-footer',
      '.recommend-list',
      '.doc-recommend',
      '.doc-operate',
      '.doc-banner',
      '.site-header',
      '.site-nav',
      '.site-footer',
      'nav',
      '.toc',
      '.sidebar',
      // rno- 前缀噪音（腾讯云开发者社区）
      '.rno-crumb',
      '.rno-breadcrumb',
      '.rno-metas',
      '.rno-meta',
      '.rno-tags',
      '.rno-tag',
      '.rno-tag-list',
      '.rno-author',
      '.rno-author-info',
      '.rno-user',
      '.rno-user-card',
      '.rno-related',
      '.rno-related-list',
      '.rno-recommend',
      '.rno-recommend-list',
      '.rno-aside',
      '.rno-sidebar',
      '.rno-nav',
      '.rno-header',
      '.rno-footer',
      '.rno-toolbar',
      '.rno-actions',
      '.rno-action-bar',
      '.rno-vote',
      '.rno-collect',
      '.rno-share',
      '.rno-comment',
      '.rno-comments',
      '.rno-ad',
      '.rno-banner',
      '.rno-promotion',
      '.rno-product',
      '.rno-trial',
      '.rno-free-trial',
      '.rno-back-top',
      '.rno-float',
      // 开发者社区非 rno- 命名的常见容器
      '.com-2-media',
      '.com-user-trigger',
      '.author-wrapper',
      '.author-panel',
      '.J-relatedArticle',
      '.J-recommendArticle',
      '.J-authorInfo',
      '.J-articleTags',
      '.J-articleActions',
      '.article-crumb',
      '.article-author-info',
      '.article-metas',
      '.free-trial',
      '.trial-banner',
      '.developer-footer',
      '.developer-nav',
      '.developer-header',
      // 底部归档/推荐
      '.archives',
      '.archive',
      '.author-info',
      '.author-card',
      '.article-footer-ext',
      '.recommend-box',
      '.recommend-news',
      '.related-doc',
      '.doc-related',
      '.read-more',
      '.hot-news',
      '.hot-list',
      '.newest-news',
      '.module-cmt',
      '.discuss',
      '#discuss',
      '.article-declare',
      '.doc-declare',
      '.copyright-declare',
      '.copy-right',
      '.praise-box',
      '.reward-box',
      '.donate-box',
      '.appreciate-box',
      '.vip-tips',
      '.member-tips',
      '.login-tips',
      '.consult',
      '.consult-bar',
      '.doc-consult',
      '.online-service',
      '.feedback-bar',
      '.doc-feedback',
      '.bottom-bar',
      '.gotop',
      '.back-top',
      '.float-layer',
      '.float-window',
      '.side-float',
      '.notice-bar',
      '.corner-ad',
      '.related-products',
      '.recommend-pro',
      '.article-product',
      '.doc-product',
      // 腾讯云开发者博客文章页补充噪音
      '.article-header',
      '.article-desc',
      '.article-tags',
      '.article-tag-list',
      '.article-vote',
      '.article-actions',
      '.article-operate',
      '.article-tool',
      '.article-collect',
      '.article-praise',
      '.article-reward',
      '.article-bottom-bar',
      '.article-copyright-box',
      '.article-statement',
      '.article-notice',
      '.recommend-article-list',
      '.related-reading',
      '.related-article-list',
      '.recommend-reading',
      '.module-recommend',
      '.mod-recommend',
      '.recommend-mod',
      '.card-recommend',
      '.recommend-card',
      '.hot-article',
      '.product-promo',
      '.product-recommend',
      '.tencent-product',
      '.promotion-card',
      '.activity-banner',
      '.discuss-area',
      '.article-catalog',
      '.article-directory',
      '.article-sidebar',
    ],
    noiseClassKeywords: [
      'nav',
      'header',
      'footer',
      'sidebar',
      'promo',
      'coupon',
      'banner',
      'recommend',
      'ad',
      'archive',
      'article-info',
      'doc-info',
      'column-info',
      'author',
      'meta',
      'comment',
      'related',
      'reward',
      'action',
      'tag',
      'copyright',
      'operate',
      'donate',
      'praise',
      'declare',
      'discuss',
      'qrcode',
      'tips',
    ],
    enableDensityOptimization: true,
    blockTagThreshold: 8,
    titleSelectors: ['h1', '.title', '.article-title', '.post-title'],
  },

  // ===== 知乎（已接入统一提取器） =====
  'zhihu.com': {
    contentSelectors: [
      // 回答页：优先命中「回答正文」容器（含图片），其首个匹配即主回答正文，
      // 避免被首页/问题简短描述等短 .RichText 干扰导致正文选错/为空。
      '.AnswerCard .RichText',
      '.AnswerItem .RichContent .RichText',
      '.RichContent .RichText',
      '.ContentItem-RichText',
      '.ContentItem-RichText .RichText',
      // 专栏文章页：命中专栏正文容器（含图片）。
      '.Post-RichTextContainer .RichText',
      '.Post-content',
      '.Post-RichText',
      '.Post-RichText-inner',
      '.RichText-inner',
      '.zhuanlan-article',
      '.zhuanlan-Post-body',
      'div[itemprop="articleBody"]',
      '.RichText.ztext',
      '.CopyrightRichText-richText',
      // 通用兜底（回答页/专栏页均可能命中）。
      '.RichText',
      '.RichText--able',
      '.RichContent-inner',
      '.Post-Main',
      'article',
      '.content',
    ],
    cleanupSels: [
      '.Advertisement',
      '.AdImageCard',
      '.Banner',
      '[class*="Banner"]',
      '.FeedItem',
      '.Recommendation-Item',
      '.HotRecommend',
      '.GlobalRecommend',
      '.Post-RelatedRecommend',
      '.RichText-LinkCard',
      '[data-za-detail-view-id*="Recommend"]',
      '.Card',
      '.Column',
      '.ContentItem-actions',
      '.Reward',
      '.Modal',
      '.Modal-wrapper',
      '.SignFlow',
      '.signFlowModal',
      '.AuthorInfo',
      '.AuthorInfo-wrapper',
      '.Post-Actions',
      '.BottomActions',
      '.RecommendArticles',
      '.Recommendation',
      '.RichCard',
      '.MCard',
      // 文末商品卡片 / 带货 / 商业推广（图3 文末无关信息主因）
      '.CommercialAd',
      '.commercial-ad',
      '.ZDInsertView',
      '.GoodsCard',
      '.goods-card',
      '.KfeCollection',
      '.MerchandiseCard',
      '.RichText-EntityWord',
      '.Pc-word',
      '.CardBrand',
      '.ClientOnly',
      // 文末评论区 / 互动区 / 表情
      '.Comments-container',
      '.CommentsV2',
      '.CommentListV2',
      '.Comment',
      '.comment',
      '.Post-topicsAndReviews',
      '.Post-NormalSub',
      '.Reward-container',
      '.VoteButton',
      '.RewardInfo',
      // 文末相关推荐 / 更多回答 / 热门搜索
      '.RelatedReadings',
      '.Recommendations-Main',
      '.Recommendations-Item',
      '.Recommendations',
      '.Post-SideActions',
      '.Post-related',
      '.Post-RelatedRecommend',
      '.MoreAnswers',
      '.ViewAll',
      '.Question-Main .List',
      '.QuestionAnswers-answerButton',
      // 知乎热搜 / 大家都在搜 / 搜索入口
      '.HotSearch',
      '.HotSearchList',
      '.HotSearchItem',
      '.TopSearch',
      '.TopSearchList',
      '.SearchCard',
      '.Search-Entrance',
      '.SearchEntrance',
      '.RecommendSearch',
      '.SearchRecommend',
      '.Recommendations-Question',
      '.Recommendations-Collection',
      '.ExploreMore',
      '.DiscoverMore',
      '.ReadMore',
      '.ArticleRead',
      '.ArticleReadList',
      // 广告 / 商品 / 带货 / 商业推广（图3 文末无关信息主因）
      '.CommercialAd',
      '.commercial-ad',
      '.ZDInsertView',
      '.GoodsCard',
      '.goods-card',
      '.KfeCollection',
      '.MerchandiseCard',
      '.RichText-EntityWord',
      '.Pc-word',
      '.CardBrand',
      '.ClientOnly',
      '.Ad',
      '.ad',
      '.Ads',
      '.ads',
      '.Advertisement',
      '.AdImage',
      '.ImageAd',
      '.AdBelowArticle',
      '.AdBelowAnswer',
      '.Banner-ad',
      '.Sticky-Inner',
      '.Sticky',
      // 知乎品牌/赞助/带货/App 推广
      '.BrandQuestion',
      '.BrandAnswer',
      '.BrandCard',
      '.PaidContent',
      '.SponsoredContent',
      '.SponsoredCard',
      '.CreatorPromotion',
      '.KOLRecommend',
      '.AppBanner',
      '.OpenInApp',
      '.AppDownload',
      '.MobileApp',
      '.AppPromotion',
      '.Related-products',
      '.KfeCollection-Related',
      '.ContentItem-more',
      '.Post-Sub',
      '.Post-NormalSub',
      '.RichText-MCN',
      '.MCN',
      '.CardV1',
      '.CardV2',
      '.feed-card',
      '.feed-item',
      '.List-item',
      '.RichText-Card',
      '.RichText-Image',
      '.Brand',
      '.brand',
      '.ecom',
      '.ecommerce',
      '.Promotion',
      '.promotion',
      '.Hot-Item',
      '.HotTopic',
      '.Topstory-Item',
    ],
    noiseClassKeywords: ['nav', 'header', 'footer', 'sidebar', 'promo', 'coupon', 'banner', 'recommend', 'ad', 'authorinfo', 'comment', 'commercial', 'goods', 'reward'],
    enableDensityOptimization: false,
    titleSelectors: ['h1', '.Post-Title', '.ArticleItem-Title', '.title'],
  },

  // ===== CSDN（扩展位，本轮仅兜底能出内容，不精细调优） =====
  'csdn.net': {
    contentSelectors: [
      '#content_views', // CSDN 博客正文主容器
      '.article_content',
      '.blog-content-box',
      'article',
      'main',
    ],
    cleanupSels: [
      '.blog-sidebar',
      '.recommend-box',
      '.template-box',
      '.article-bar',
      '.csdn-sidebar',
      '#asideProfile',
      '.recommend',
      '.comment-box',
      '.comment-list',
      '#commentBox',
      '.article-info-box',
      '.article_directory',
      '#toc',
      '.catalog',
      '.article-copyright',
      '.article-footer',
      '.copyright-info',
      '#recommendArticles',
      '.related-articles',
      '.article-bottom',
      '.read-next',
      '.article_collect',
      '.toolbar',
      '.reward',
      '.praise',
      '.follow-box',
      '.tool-box',
      '.article-header-bar',
      '.bar-content',
      '.blog_container_aside',
      '.aside-box',
      '.left-toolbox',
      '.right-toolbox',
      '.tool-box-blog',
      '.login-mark',
      '.login-box',
      '.vip-box',
      '.more-toolbox',
      '.comment-edit-box',
      '.comment-list-container',
      '.recommend-item-box',
      '.hot-article',
      '.hot-column',
      '.article-type-img',
      '.article-type-text',
      '.top-ads',
      '.ads-box',
      // 高把握噪音（底部/推荐/标签/搜索/广告）
      '.blog-footer',
      '.recommend-blog',
      '.relevant-article',
      '.relevant',
      '.csdn-ad',
      '.recommend-ad',
      '.baidu-search',
      '.blog-nav',
      '.article-tags',
      '.blog-tags',
      // CSDN 底部推荐/作者/工具栏补充（2026-07-16）
      '#recommendBlogs',
      '.recommend-blogs',
      '.blog-expert-recommend',
      '.csdn-side-toolbar',
      '#csdn-toolbar',
      '.csdn-common-btns',
      '.csdn-bbs',
      '.programmers',
      '.user-desc',
      '.user-info',
      '.blog_title',
      '.bar-top',
      '.blog_container_r',
      '.tool-active',
      '.slide-content',
      '.recommend-type',
      '.recommend-type-box',
      '.recommend-loading',
      '.more',
      '.extension',
      '.ads',
      '.adsbygoogle',
      '.google-ad',
      // CSDN 末尾「相关推荐 / 猜你喜欢 / 热门」补充（2026-07-16）
      '.article-recommend',
      '.recommend-list',
      '.recommend-item',
      '.more-recommend',
      '.recommend-more',
      '.guess-you-like',
      '.guess-like',
      '.hot-recommend',
      '.recommend-column',
      '.recommend-left',
      '.recommend-right',
      '#recommendInside',
      '.article-recommend-list',
      '.recommend-panel',
      '.related-recommend',
      '.recommend-article',
      '.recommend-articles',
      '.bottom-recommend',
      '.footer-recommend',
      '.recommend-mod',
    ],
    noiseClassKeywords: ['nav', 'header', 'footer', 'sidebar', 'promo', 'coupon', 'banner', 'recommend', 'ad', 'comment', 'related', 'tool', 'copyright', 'directory', 'catalog', 'aside', 'collect', 'praise', 'reward'],
    enableDensityOptimization: true,
    blockTagThreshold: 8,
    titleSelectors: ['h1', '.title-article', '.article-title'],
  },

  // ===== 博客园（完整配置，解决导航残留问题） =====
  'cnblogs.com': {
    contentSelectors: [
      '#cnblogs_post_body',
      '.postBody',
      '#post_detail',
      '.post',
      'article',
    ],
    cleanupSels: [
      '#blog_nav',
      '.blognav',
      '.nav-menu',
      '#navList',
      '.blogStats',
      '.postDesc',
      '#sideBar',
      '#blog-sidecolumn',
      '#blog-comments-placeholder',
      '#comment_form_container',
      '#tbCommentBody',
      '#under_post_kb',
      '#under_post_card',
      '.dayTitle',
      '.postBottom',
      '#footer',
      '#colophon',
      '.authorProfile',
      '.post-meta',
    ],
    noiseClassKeywords: ['nav', 'header', 'footer', 'sidebar', 'promo', 'coupon', 'banner', 'recommend', 'ad', 'blognav'],
    enableDensityOptimization: true,
    blockTagThreshold: 8,
    titleSelectors: ['h1', '.postTitle', '.entry-title', 'title'],
  },
};
